Revert timeout version of script to previous state
Turns out this strategy doesn't work in the end. Oddly enough it worked
for a simple test of using `grep` and `grep --help` to test it but it
did not work with the PostgreSQL example from the docs.

It always caused a timeout and it also ate all of the stdout / stderr in
that case.

diff --git a/wait-until b/wait-until
--- a/wait-until
+++ b/wait-until
@@ -3,8 +3,14 @@
 command="${1}"
 timeout="${2:-30}"
 
-timeout "${timeout}" bash -c "until ${command}; do sleep 1; done" \
-|| (
-    >&2 printf "command was never successful, aborting due to %s s timeout!\n" "${timeout}"
-    exit 1
-)
+i=0
+until eval "${command}"
+do
+    sleep 1
+    ((i++))
+
+    if [ "${i}" -gt "${timeout}" ]; then
+        echo "command was never successful, aborting due to ${timeout}s timeout!"
+        exit 1
+    fi
+done
